[project]
authors = ["CFeller <clement.feller@obspm.fr>"]
channels = ["conda-forge"]
description = "Translating support material for gouarin/splineart-cpp"
name = "splineart-doc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
